- name: add nginx yum repository
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644
  
- name: install nginx
  yum: name=nginx

- name: move default nginx conf to bak
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.default

- name: setting nginx conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  
- name: setting rails conf
  template: src=rails.conf dest=/etc/nginx/conf.d/rails.conf owner=root group=root mode=0644

- name: start nginx
  service: name=nginx state=started enabled=yes
