- name: Install nvm
  shell: "wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash"
  become: yes
  become_user: "{{ rbenv_user }}"
    
- name: Install node
  shell: bash -lc "nvm install node"
  become: yes
  become_user: "{{ rbenv_user }}"
