- name: Install node
  shell: "sudo curl --silent --location https://rpm.nodesource.com/setup_7.x | bash -"
    
- name: Add npm yarn
  shell: "wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo"
  
- name: Install yarn
  yum: name=yarn
