- name: Install node
  shell: "curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -"
  become: yes
  become_user: "{{ rbenv_user }}"
    
- name: Add npm yarn
  shell: "wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo"
  become: yes
  become_user: "{{ rbenv_user }}"
  
- name: Install yarn
  yum: name=yarn
