- name: install postgresql95
  yum: name={{ item }}
  with_items:
    - postgresql95-devel
    - postgresql95-server
    - postgresql95-contrib

- name:  initialize postgresql95
  shell: service postgresql95 initdb
#   become: true
#   become_user: "postgres"

# - name: backup pg_hba.conf
#   shell: mv /var/lib/pgsql95/data/pg_hba.conf /var/lib/pgsql95/data/pg_hba.conf.default

# - name: pg_hba.conf setting
#   copy: src=pg_hba.conf dest=/var/lib/pgsql95/data/pg_hba.conf owner=postgres group=postgres mode=0600

- name: start postgresql95
  service: name=postgresql95 state=started enabled=yes

