- name: install postgresql
  yum: name={{ item }}
  with_items:
    - postgresql-devel
    - postgresql-server
    - postgresql-contrib

- name:  initialize postgresql
  shell: postgresql-setup initdb
  become: true
  become_user: "postgres"

- name: backup pg_hba.conf
  shell: mv /var/lib/pgsql/data/pg_hba.conf /var/lib/pgsql/data/pg_hba.conf.default

- name: pg_hba.conf setting
  copy: src=pg_hba.conf dest=/var/lib/pgsql/data/pg_hba.conf owner=postgres group=postgres mode=0600

- name: start postgresql
  service: name=postgresql state=started enabled=yes

